# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {}
  required_version = " >= 1.0, <= 1.5.7 "
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = " >=4.15.1, <=4.67.0"
    }
  }
}

provider "aws" {
  region = "us-west-2"
}
